setwd("~/myrepos/sta250/Stuff/HW2/HiveBasics/")
rm(list = ls())
gmeans <- read.table("group_means.txt")
names(gmeans) <- c("group", "mean")
gpop_vars <- read.table("group_pop_vars.txt")
names(gpop_vars) <- c("group", "pop_variance")
gunbiased_sample_vars <- read.table("group_unbiased_sample_vars.txt")
names(gunbiased_sample_vars) <- c("group", "sample_variance")
#par(mfrow = c(1,2), cex = 0.5)
pdf("mean_on_var.pdf")
plot(gmeans$mean, gpop_vars$pop_variance, pch  = 19, main = "Pop. Variance on Mean (Within Groups)")
dev.off()
